spring:
  application:
    name: csrf-reactive
  main:
    banner-mode: off

management:
  tracing:
    enabled: true
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
        - health
        - info
        - loggers
        - metrics
        - prometheus

logging:
  level:
    it:
      poli: debug
