spring:
  application:
    name: csrf-reactive
  main:
    banner-mode: off

management:
  endpoint:
    loggers:
      enabled: true
    info:
      enabled: true

logging:
  level:
    it:
      poli: debug
